import Head from 'next/head';
import Image from 'next/image';
import ArticleList from '../components/ArticleList';

export default function Home({articles}) {
	console.log(articles);
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				Hello World
				<br />
                <p className="text-cyan-700 text-2xl">Irving Zamora</p>
			</main>
			<ArticleList articles={articles} />
		</div>
	);
}

export const getStaticProps = async () => {
	const res = await fetch(`http://jsonplaceholder.typicode.com/posts?_limit=6`)
	const articles = await res.json()

	return {
		props: {articles}
	}
}